apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  namespace: efklog
  labels:
    k8s-app: elasticsearch-logging
    app.kubernetes.io/instance: elasticsearch-logging
    app.kubernetes.io/name: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: elasticsearch-logging