apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd-es
  namespace: efklog
  labels:
    app.kubernetes.io/name: fluentd-es
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-es
  labels:
    app.kubernetes.io/name: fluentd-es
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-es
  labels:
    app.kubernetes.io/name: fluentd-es
subjects:
- kind: ServiceAccount
  name: fluentd-es
  namespace: efklog
roleRef:
  kind: ClusterRole
  name: fluentd-es
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-es-v4.2.2
  namespace: efklog
  labels:
    app.kubernetes.io/name: fluentd-es
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentd-es
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluentd-es
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      serviceAccountName: fluentd-es
      containers:
      - name: fluentd-es
        image: fluent/fluentd:v1.14.3-debian-1.0
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: config-volume
          mountPath: /fluentd/etc/fluentd.conf
          subPath: fluentd.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: config-volume
        configMap:
          name: fluentd-es-config-v0.2.0